### ISSUE TITLE
Build Error(Rust 1.82.0)

### ISSUE THREAD

**Issue by ANseunghyeon** [heinzelotto/rust-callgraph#4]
Hello, i can't solve this error. 

> $ cargo install --debug --locked --path . --force
  Installing callgraph v0.1.0 (/home/an/rust-callgraph)
    Updating crates.io index
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling serde v1.0.204
   Compiling semver v1.0.23
   Compiling serde_json v1.0.122
   Compiling camino v1.1.7
   Compiling thiserror v1.0.63
   Compiling rustix v0.38.34
   Compiling libc v0.2.155
   Compiling itoa v1.0.11
   Compiling bitflags v2.6.0
   Compiling ryu v1.0.18
   Compiling linux-raw-sys v0.4.14
   Compiling memchr v2.7.4
   Compiling home v0.5.9
   Compiling either v1.13.0
   Compiling quote v1.0.36
   Compiling syn v2.0.72
   Compiling wait-timeout v0.2.0
   Compiling which v6.0.2
   Compiling serde_derive v1.0.204
   Compiling thiserror-impl v1.0.63
   Compiling cargo-platform v0.1.8
   Compiling rustc_version v0.4.0
   Compiling cargo_metadata v0.18.1
   Compiling callgraph v0.1.0 (/home/an/rust-callgraph)

> 

> warning: unused import: `Node`
> 
>  --> src/visitor.rs:1:24
>   |
> 1 | use rustc_hir::{HirId, Node};
>   |                        ^^^^
>   |
>   = note: `#[warn(unused_imports)]` on by default
> 
> warning: unused import: `rustc_middle::hir::map::Map`
>  --> src/visitor.rs:4:5
>   |
> 4 | use rustc_middle::hir::map::Map;
>   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> warning: unused import: `rustc_middle::ty::TypeckResults`
>  --> src/visitor.rs:5:5
>   |
> 5 | use rustc_middle::ty::TypeckResults;
>   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> warning: the feature `backtrace` has been stable since 1.65.0 and no longer requires an attribute to enable
>  --> src/lib.rs:1:12
>   |
> 1 | #![feature(backtrace)]
>   |            ^^^^^^^^^
>   |
>   = note: `#[warn(stable_features)]` on by default
> 
> error[E0308]: mismatched types
>    --> src/visitor.rs:166:13
>     |
> 107 |         match expr.kind {
>     |               --------- this expression has type `rustc_hir::ExprKind<'_>`
> ...
> 166 |             None => (),
>     |             ^^^^ expected `ExprKind<'_>`, found `Option<_>`
>     |
>     = note: expected enum `rustc_hir::ExprKind<'_>`
>                found enum `std::option::Option<_>`
> help: try wrapping the pattern in `rustc_hir::ExprKind::Ret`
>     |
> 166 |             rustc_hir::ExprKind::Ret(None) => (),
>     |             +++++++++++++++++++++++++    +
> 
> For more information about this error, try `rustc --explain E0308`.
> warning: `callgraph` (lib) generated 4 warnings
> error: could not compile `callgraph` (lib) due to 1 previous error; 4 warnings emitted
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `callgraph v0.1.0 (/home/an/rust-callgraph)`, intermediate artifacts can be found at `/home/an/rust-callgraph/target`.
> To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by vikramnitin9** [comment]
Thanks for catching that. Fixed in e263be3c938b23bf8ab936e9201c7dd1cf6f2257

**Comment by ANseunghyeon** [comment]
Thank you so much for the quick update!!

I've built a modified code, and it's built well.

However, when I ran it on the next step, exmple_code, I encountered the following error.

I really want to use this tool, but I can't solve it by myself, so I'm asking.

I truly appreciate all your efforts.
____________________________________

> ~/rust-callgraph/example_code$ RUST_BACKTRACE=1 cargo callgraph
> Running cargo callgraph
> Target name: example_code
>     Checking example_code v0.1.0 (/home/an/rust-callgraph/example_code)
> Running cargo rustc
> thread 'rustc' panicked at src/visitor.rs:155:18:
> not yet implemented
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/library/std/src/panicking.rs:662:5
>    1: core::panicking::panic_fmt
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/library/core/src/panicking.rs:74:14
>    2: core::panicking::panic
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/library/core/src/panicking.rs:148:5
>    3: <callgraph::visitor::CallgraphVisitor as rustc_hir::intravisit::Visitor>::visit_expr
>              at /home/an/rust-callgraph/src/visitor.rs:155:18
>    4: rustc_hir::intravisit::walk_body
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_hir/src/intravisit.rs:589:5
>    5: rustc_hir::intravisit::Visitor::visit_body
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_hir/src/intravisit.rs:304:9
>    6: rustc_hir::intravisit::Visitor::visit_nested_body
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_hir/src/intravisit.rs:288:24
>    7: rustc_hir::intravisit::walk_fn
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_hir/src/intravisit.rs:1018:5
>    8: rustc_hir::intravisit::Visitor::visit_fn
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_hir/src/intravisit.rs:394:9
>    9: rustc_hir::intravisit::walk_item
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_hir/src/intravisit.rs:511:24
>   10: <callgraph::visitor::CallgraphVisitor as rustc_hir::intravisit::Visitor>::visit_item
>              at /home/an/rust-callgraph/src/visitor.rs:169:42
>   11: rustc_middle::hir::map::Map::visit_all_item_likes_in_crate
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_middle/src/hir/map/mod.rs:441:9
>   12: callgraph::analyze
>              at /home/an/rust-callgraph/src/lib.rs:41:5
>   13: <callgraph::CallgraphCallbacks as rustc_driver_impl::Callbacks>::after_analysis::{{closure}}
>              at /home/an/rust-callgraph/src/bin/callgraph.rs:19:13
>   14: rustc_middle::ty::context::GlobalCtxt::enter::{{closure}}
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_middle/src/ty/context.rs:1331:37
>   15: rustc_middle::ty::context::tls::enter_context::{{closure}}
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_middle/src/ty/context/tls.rs:82:9
>   16: std::thread::local::LocalKey<T>::try_with
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/library/std/src/thread/local.rs:283:12
>   17: std::thread::local::LocalKey<T>::with
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/library/std/src/thread/local.rs:260:9
>   18: rustc_middle::ty::context::tls::enter_context
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_middle/src/ty/context/tls.rs:79:9
>   19: rustc_middle::ty::context::GlobalCtxt::enter
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_middle/src/ty/context.rs:1331:9
>   20: rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>::enter
>              at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_interface/src/queries.rs:65:9
>   21: <callgraph::CallgraphCallbacks as rustc_driver_impl::Callbacks>::after_analysis
>              at /home/an/rust-callgraph/src/bin/callgraph.rs:18:9
>   22: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> error: could not compile `example_code` (bin "example_code")
> Finished with non-zero exit code

**Comment by vikramnitin9** [comment]
Gosh I'm sorry, I don't know how these errors crept in. I think I was managing multiple versions and when I tried to consolidate them, I got my wires crossed.

I replaced the `todo!()` with `{}`. Now it should run without errors. Fixed in 4e1e6d38cbafc3db60aca70fde6b19d152ca95e6

**Comment by ANseunghyeon** [comment]
It’s working perfectly now, thanks to your help. I truly appreciate it!

If it's not too much trouble, I’m hoping to apply this to some of other projects(Prompt-Fuzz project https://github.com/PromptFuzz/PromptFuzz), but I’m a bit unsure about how to proceed. I’d be so grateful if you could offer some guidance!!

I apologize for taking up your time, but your help has been invaluable, and I can't thank you enough!

**Comment by vikramnitin9** [comment]
`cargo callgraph` should work straight out of the box.
